"""Configuration wizard option constants for the CLI."""

MODEL_PROVIDER_ENV = "MODEL_PROVIDER"
NOTIFICATION_PLATFORM_ENV = "NOTIFICATION_PLATFORM"
CODE_REPOSITORY_PROVIDER_ENV = "CODE_REPOSITORY_PROVIDER"
DEPLOYMENT_PLATFORM_ENV = "DEPLOYMENT_PLATFORM"
LOGGING_PLATFORM_ENV = "LOGGING_PLATFORM"
LEGACY_SELECTION_ENV_KEYS: tuple[str, ...] = (
    MODEL_PROVIDER_ENV,
    NOTIFICATION_PLATFORM_ENV,
    CODE_REPOSITORY_PROVIDER_ENV,
    DEPLOYMENT_PLATFORM_ENV,
    LOGGING_PLATFORM_ENV,
)

MODEL_PROVIDER_ANTHROPIC = "anthropic"
NOTIFICATION_PLATFORM_SLACK = "slack"
CODE_REPOSITORY_PROVIDER_GITHUB = "github"
DEPLOYMENT_PLATFORM_AWS = "aws"
LOGGING_PLATFORM_CLOUDWATCH = "cloudwatch"

MODEL_PROVIDER_CHOICES: tuple[tuple[str, str], ...] = (("Anthropic", MODEL_PROVIDER_ANTHROPIC),)
NOTIFICATION_PLATFORM_CHOICES: tuple[tuple[str, str], ...] = (
    ("Slack", NOTIFICATION_PLATFORM_SLACK),
)
CODE_REPOSITORY_PROVIDER_CHOICES: tuple[tuple[str, str], ...] = (
    ("GitHub", CODE_REPOSITORY_PROVIDER_GITHUB),
)
DEPLOYMENT_PLATFORM_CHOICES: tuple[tuple[str, str], ...] = (("AWS", DEPLOYMENT_PLATFORM_AWS),)
AWS_LOGGING_PLATFORM_CHOICES: tuple[tuple[str, str], ...] = (
    ("CloudWatch", LOGGING_PLATFORM_CLOUDWATCH),
)
